# Generated by Django 3.2.3 on 2021-06-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('whatched', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
